insert into test.customer (  creation_date, customer_number, description, state)
values ( '2022-12-01', '123D4567891', 'Test-1', 'IN_PROGRESS');

insert into test.customer (  creation_date, customer_number, description, state)
values   ('2022-12-02', '123D4567891', 'Test-2', 'IN_PROGRESS');

insert into test.customer (  creation_date, customer_number, description, state)
values   ('2022-12-03', '123D4567891', 'Test-3', 'IN_PROGRESS');

insert into test.customer (  creation_date, customer_number, description, state)
values   ('2022-12-04', '123D4567891', 'Test-4', 'IN_PROGRESS');

insert into test.customer (  creation_date, customer_number, description, state)
values   ('2022-12-05', '123D4567891', 'Test-5', 'IN_PROGRESS');

insert into test.customer (  creation_date, customer_number, description, state)
values   ('2022-12-06', '123D4567891', 'Test-6', 'IN_PROGRESS');

insert into test.customer (  creation_date, customer_number, description, state)
values   ('2022-12-07', '123D4567891', 'Test-7', 'IN_PROGRESS');

insert into test.customer (  creation_date, customer_number, description, state)
values   ('2022-12-08', '123D4567891', 'Test-8', 'IN_PROGRESS');

insert into test.customer (  creation_date, customer_number, description, state)
values   ('2022-12-09', '123D4567891', 'Test-9', 'IN_PROGRESS');

insert into test.customer (  creation_date, customer_number, description, state)
values   ('2022-12-10', '123D4567891', 'Test-10', 'IN_PROGRESS');

insert into test.customer (  creation_date, customer_number, description, state)
values   ('2022-12-11', '123D4567891', 'Test-11', 'IN_PROGRESS');

insert into test.customer (  creation_date, customer_number, description, state)
values   ('2022-12-12', '123D4567891', 'Test-12', 'IN_PROGRESS');

insert into test.customer (  creation_date, customer_number, description, state)
values   ('2022-12-13', '123D4567891', 'Test-13', 'IN_PROGRESS');

insert into test.customer (  creation_date, customer_number, description, state)
values   ('2022-12-14', '123D4567891', 'Test-14', 'IN_PROGRESS');

insert into test.customer (  creation_date, customer_number, description, state)
values   ('2022-12-15', '123D4567804', 'Test-15', 'IN_PROGRESS');

insert into test.customer (  creation_date, customer_number, description, state)
values   ('2022-12-16', '123D4567804', 'Test-16', 'IN_PROGRESS');

insert into test.customer (  creation_date, customer_number, description, state)
values   ('2022-12-17', '123D4567804', 'Test-17', 'IN_PROGRESS');

insert into test.customer (  creation_date, customer_number, description, state)
values   ('2022-12-18', '123D4567804', 'Test-18', 'IN_PROGRESS');

insert into test.customer (  creation_date, customer_number, description, state)
values   ('2022-12-19', '123D4567804', 'Test-19', 'IN_PROGRESS');

insert into test.customer (  creation_date, customer_number, description, state)
values   ('2022-12-20', '123D4567804', 'Test-20', 'IN_PROGRESS');

insert into test.customer (  creation_date, customer_number, description, state)
values   ('2022-12-21', '123D4567804', 'Test-21', 'IN_PROGRESS');

insert into test.customer (  creation_date, customer_number, description, state)
values   ('2022-12-22', '123D4567804', 'Test-22', 'IN_PROGRESS');

insert into test.customer (  creation_date, customer_number, description, state)
values   ('2022-12-23', '123D4567804', 'Test-23', 'IN_PROGRESS');

insert into test.customer (  creation_date, customer_number, description, state)
values   ('2022-12-24', '123D4567804', 'Test-24', 'IN_PROGRESS');

insert into test.customer (  creation_date, customer_number, description, state)
values   ('2022-12-25', '123D4567804', 'Test-25', 'IN_PROGRESS');

insert into test.customer (  creation_date, customer_number, description, state)
values   ('2022-12-26', '123D4567804', 'Test-26', 'IN_PROGRESS');

insert into test.customer (  creation_date, customer_number, description, state)
values   ('2022-12-27', '123D4567804', 'Test-27', 'IN_PROGRESS');

insert into test.customer (  creation_date, customer_number, description, state)
values   ('2022-12-28', '123D4567804', 'Test-28', 'IN_PROGRESS');

insert into test.customer (  creation_date, customer_number, description, state)
values   ('2022-12-29', '123D4567804', 'Test-29', 'IN_PROGRESS');

insert into test.customer (  creation_date, customer_number, description, state)
values   ('2022-12-30', '123D4567804', 'Test-30', 'IN_PROGRESS');

insert into test.customer (  creation_date, customer_number, description, state)
values   ('2022-12-31', '123D4567804', 'Test-31', 'IN_PROGRESS');
